name: Release

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia a la versión de Node.js que necesites

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Usar el token de acceso personal
        run: npm run release
